package com.security.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.security.JwtUtil;
import com.security.entity.UserEntity;
import com.security.entity.UserRequest;
import com.security.entity.UserResponse;
import com.security.service.userService;

@RestController
@RequestMapping("/user")
public class UserController {
	
	@Autowired
	private userService userService;
	
	@Autowired
	private JwtUtil util;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	
	@PostMapping("/adduser")
	public ResponseEntity<String> saveuser(@RequestBody UserEntity userEntity){
		
		Integer id=userService.saveuser(userEntity);
		String body="user"+id+"saved";
		return new ResponseEntity<String>(body,HttpStatus.OK);
	}
	
	//validate user and generate token(login)
	
	@PostMapping("/login")
  public ResponseEntity<UserResponse> loginUser(
		  @RequestBody UserRequest request)
  {
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						request.getUsername(), request.getPassword()));
		
	  String token=util.generateToken(request.getUsername());
	 return ResponseEntity.ok(new UserResponse(token,"Success! generated by nikhil"));
  }
	
	
	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal p)
	{
		return ResponseEntity.ok("Hello User" + p.getName());
	}

}
